# Generated by Django 4.0.1 on 2022-08-18 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='fk_id_usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='responsables_pro',
            field=models.ManyToManyField(related_name='proyectos', to='api.Miembro', verbose_name='Responsables'),
        ),
        migrations.AddField(
            model_name='libro',
            name='autores_lib',
            field=models.ManyToManyField(related_name='libros', to='api.Miembro', verbose_name='Autores'),
        ),
        migrations.AddField(
            model_name='congreso',
            name='autores_con',
            field=models.ManyToManyField(related_name='congresos', to='api.Miembro', verbose_name='Autores'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='autores_art',
            field=models.ManyToManyField(related_name='articulos', to='api.Miembro', verbose_name='Autores'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='fk_id_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto', verbose_name='Proyecto'),
        ),
    ]
